<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Value Objects\**" />
    <EmbeddedResource Remove="Value Objects\**" />
    <None Remove="Value Objects\**" />
  </ItemGroup>

</Project>
